version: "1"
rules:
  - base: main
    upstream: gr2m:main
    mergeMethod: hardreset
    mergeUnstable: true
  - base: latest
    upstream: main
    conflictReviewers:
      - wei
    mergeMethod: merge
